### ISSUE TITLE
Week 4: Downloading your image!

### ISSUE THREAD

**Issue by ganning127** [ganning127/hello#6]
Week 4 Step 4 ⬤⬤⬤⬤◯◯◯ | 🕐 Estimated completion: 5-20 minutes

#### Demo: [🐰](https://week4step4.emilychen10.repl.co/)
*Write and connect a JS file to make a GET request to the download Azure function that includes the codename to receive the link. Edit the button on the HTML page so that it downloads the file when clicked.*

<p align="center">
   <img src="https://user-images.githubusercontent.com/69332964/121591935-14a77500-ca08-11eb-80bb-e2f286e52d0e.png" width="500" height="300" />
</p>

### ✅  Task:
- [ ] Make sure you're on the `bunnimage-frontend` branch
- [ ] Add an attribute of `id` with the value `button1` onto the upload button
- [ ] Create a new input field with an `id` of `downloadusername` and create a button with an `id` of `button2` that calls the function `downloadImage()` in `index.html` 
- [ ] Create the `downloadImage()` function with a `await fetch` GET request to send `downloadusername` to your Bunnimage Azure Function to return the file download uri
- [ ] If the fetch was successful, open the file download link using [`window.open()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) and make sure it replaces the page instead of opening a new tab.
- [ ] Commit your updated code to `bunnimage/index.html` and `bunnimage/script.js`

### 🚧 Test your Work
Open up your LiveServer plugin and start your local server. **To test your web app:**

⚠️ Type in the username for an image you have uploaded previously. Does the download button link to your file?

### Opening a link

[`window.open()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open) is fairly straightforward to use. Here's the syntax:
```js
window.open(URL, name, specs, replace)
```
We will only be using `URL` and `name`. Use [this documentation](https://www.w3schools.com/jsref/met_win_open.asp) to fill it in.
